version: '3.8'

services:
  db_container:
    image: mysql:5.7
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: daily_report_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/mysql_setup.sql:/docker-entrypoint-initdb.d/mysql_setup.sql
    ports:
      - "3306:3306"

  web_container:
    build:
      context: ./web
    container_name: web_container
    ports:
      - "8080:8080"
    depends_on:
      - db_container

volumes:
  db_data:
